name: CI-CD-HTML

env:
  SERVER_IP : ${{ secrets.YC_INSTANCE_IP }}

on: [push]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
  
    steps:
    
    - name: Git clone
      uses: actions/checkout@v3.5.3
    
    - name: List of files before
      run: ls -al

    - name: Getting ready to ssh connection
      run: |
        mkdir ~/.ssh/
        ssh-keyscan ${{ secrets.YC_INSTANCE_IP }} >> ~/.ssh/known_hosts
        echo "${{ secrets.YC_INSTANCES_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/id_rsa
    
    - name: List of files in .ssh folder
      run: ls -l ~/.ssh/
      
    - name: Zip files for transfer
      run: tar -czvf archive.tgz --exclude='*.git*' .
    
    - name: List of files after packing
      run: ls -al

    - name: Remove files in /var/www/html/
      run: ssh -i ~/.ssh/id_rsa admiral@"${{ env.SERVER_IP }}" "rm -rfv /var/www/html/*"
